# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast unpack info.
#' 
#' @param strings Vector of string to unpack
#' @param names Vector os strings of keys to unpacks
#' @returns List of unpacked values
#' 
#' @export
fast_unpack_info <- function(strings, names) {
    .Call(`_JACUSA2helper_fast_unpack_info`, strings, names)
}

